jango/Day19/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name="signup"),

    path('login/',views.login, name="login"),
    path('logout/',views.logout, name="logout")

]

jango/Day19/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('',views.article_list, name='article_list'),
    path('<int:article_id>/', views.article_detail,name='article_detail'),
    path('new/',views.new_article,name='new_article'),
    path('<int:article_id>/edit/',views.edit_article,name='edit_article'),
    path('<int:article_id>/comment/new',views.new_comment,name='new_comment'),
    path('<int>:article_id>/like/',views.toggle_like,name='toggle_like')


]

jango/Day19/django_abvance/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('accounts/',include('accounts.urls')),
]

jango/Day19/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    address = models.CharField(max_length=200)
    fans = models.ManyToManyField('self', related_name='stars')

jango/Day19/board/models.py
from django.db import models
from faker import Faker
from django.conf import settings
# Create your models here.
f = Faker()
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    keyword = models.CharField(max_length=50)
    email= models.CharField(max_length=200)
    content = models.TextField()
    date= models.DateField(blank=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles') #article_set


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def dummy(cls, n):
        for i in range(n):
            cls.objects.create(
                title=f.text(20),
                content=f.text(),
                keyword=f.company(),
                email=f.email(),
            )

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

jango/Day19/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
#from .models import User
from .models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):
    address = forms.CharField(min_length=3)
    class Meta(UserCreationForm.Meta):
        model  = User
        fields = UserCreationForm.Meta.fields + ('address',)

class CustomAuthenticationForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User

jango/Day19/board/forms.py
from django import forms

from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(min_length=2, strip=True)
    email = forms.EmailField()
    keyword = forms.CharField(min_length=1, max_length=10)
    class Meta:
        model = Article
        #fields ='__all__'   
        #exclue는 이걸 빼고 내보내겠습니다. 
        exclude = ['date','author','like_users']
   
class CommentForm(forms.ModelForm):
    content = forms.CharField(min_length=1,max_length=200)
    class Meta:
        model = Comment
        fields = ['content',]

jango/Day19/accounts/views.py
from django.shortcuts import render , redirect,get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout
from .forms import CustomAuthenticationForm, CustomUserCreationForm


def follow(request, user_id):
    fan = request.user
    star = get_object_or_404(id=user_id)
    if fan.stars.filter(id=star.id).exists():
        fan.stars.remove(star)
    else:
        fan.stars.add(star)
    return redirect('accounts:user_detail',star.id)

def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('board:article_list')
        else:
            form = CustomUserCreationForm()
        
        context = {'form':form}
        
        return render(request,'signup.html',context)
    else:
        return redirect('board:article_list')
def login(request):
    if request.user.is_authenticated:
        return redirect('board:article_list')
    else:        
        if request.method == 'POST':
            form = CustomAuthenticationForm(request, request.POST)
            
            if form.is_valid():
                user = form.get_user()
                auth_login(request, user)
                return redirect(request.GET.get('next') or 'board:article_list')
        else:
            form = CustomAuthenticationForm()
        
        context = {'form':form}
        
        return render(request,'login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('board:article_list')

jango/Day19/board/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET , require_POST

#요청이 get이나 post 설정을 해서 아니면 튕기게 한다. 

@login_required
def new_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        #is_valid는 이것이 유효 하냐 걸러서 save 한다.
        if form.is_valid():
            article = form.save(commit=False) #실제로 저장안함 
            article.author = request.user
            article.save()
            return redirect('board:article_detail',article.id)
    else:
        form = ArticleForm()
    
    context = {'form':form}
    
    return render(request,'board/article_form.html',context)




@require_GET
# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    context = {'articles':articles}
    return render(request,'board/article_list.html', context)


def article_detail(request,article_id):
    article = get_object_or_404(Article, id=article_id)
    comment_form = CommentForm()
    comments = Comment.objects.all()
    context={'article':article,
             'comment_form':comment_form,
             'comments':comments,   
            }
    return render(request,'board/article_detail.html',context)

@login_required
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        print(f'Data 넘어옴')
        if form.is_valid():
            article = form.save()
            return redirect('board:article_detail',article.id)
    else:
        form = ArticleForm(instance=article)
    
    context = {'form':form}
    
    return render(request,'board/article_form.html',context)


@login_required
@require_POST
def new_comment(request, article_id):
    article = get_object_or_404(Article, id = article_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.article_id = article_id
        comment.save() 
    return redirect('board:article_detail',article_id)

@require_POST
def toggle_like(request, article_id):
    article = get_object_or_404(Ariticle, id =article_id)
    user = request.user
    if article.like_users.filter(id=user.id).exists():
    #if user  in article.like_user.all():
        article.like_users.remove(user) 
    else:    
        article.like_users.add(user)
    return redirect('board:article_detail',article.id)
    #request.user.like_articles(article)  위와 같은 말임 

jango/Day19/board/templates/board/article_detail.html
 {% extends 'base.html' %} 
 {% load bootstrap4 %}
{% block content %}
<h1>{{article.title}}</h1>
<h2>{{ article.author }}</h2>

{% if article.author == user %}
<a href=" {% url 'board:edit_article' article.id %}">수정</a>|
<a href="">삭제</a>
{% endif %}
<small>
{{article.created_at}} | {{article.updated_at}}
</small>

<form action="{% url 'board:toggle_like' article.id %}" method='POST'>
        {% csrf_token %}
    <button class="btn btn-danger">like</button>
</form>
<p>{{article.content}}</p>
<p>
{{article.keyword}}|{{article.email}}
</p>

{% if user.is_authenticated %}
    <form action="{% url 'board:new_comment' article.id %}" method='POST'>
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        <button class="btn btn-primary">댓굴작성</button>
    </form>
    
{% else %}
로그인하세여
{% endif %}


{% for comment in comments %}
    <div>
        {{comment.content}} - {{comment.author}}
    </div>
{% empty %}
댓글이 없어요
{% endfor %}

 

{% endblock  %}

jango/Day19/board/templates/board/article_form.html
 {% extends 'base.html' %} 
 {% load bootstrap4 %}
 {% block content %}


<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <input type="submit">
</form>

 {% endblock  %}

jango/Day19/board/templates/board/article_list.html
{% extends 'base.html' %} 

{% block content %}
<h1>Article list</h1>
<ul>
{% for article in articles  %}
<li>
<a href={% url 'board:article_detail' article.id %}>{{article.title}}</a>
</li>
{% endfor %}
</ul>
{% endblock  %}

jango/Day19/board/templates/board/new_article.html
 {% extends 'base.html' %} 
 {% load bootstrap4 %}
 {% block content %}

<h1>New Article</h1>
<form action="{% url 'board:new_article'%}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    <input type="submit">
</form>

 {% endblock  %}

jango/Day19/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     {% block style %}
    {% endblock  %}
    <title>Document</title>
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock content %}

</div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>