jango/Day18/chatproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.login,name="login"),
    path('signup/',views.signup,name="signup"),
    path('logout/',views.logout,name="logout"),
 
]

jango/Day18/chatproject/boards/urls.py
from django.urls import path
from . import views

app_name = "boards"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:room_id>/exit/',views.exit,name="exit"),
    path('<int:room_id>/', views.show, name="room"),
    path('<int:room_id>/messsage',views.chat,name="chat"),
]

jango/Day18/chatproject/chatproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/',include('accounts.urls'))
]

jango/Day18/chatproject/accounts/models.py
from django.db import models

# Create your models here.

jango/Day18/chatproject/boards/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.


class Room(models.Model):
    title = models.CharField(max_length=32)
    code = models.CharField(max_length=16, unique=True)
    max_connection = models.IntegerField()
    master = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="rooms")
    #def current_connection(self):
        #return ''

class Message(models.Model):
    contents = models.TextField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

jango/Day18/chatproject/accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.


def signup(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() #회원가입
            auth_login(request, user) #로그인
            return redirect('boards:index')
        else:
            return render(request, 'signup.html')
    else:
        if request.user.is_authenticated:
            return redirect('boards:index')
        else:
            return render(request, 'signup.html')

        
def login(request):
    if request.method =='POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())#form.get.user:user 목록에서 user를 찾아서 로그인 해준다.
            return redirect('boards:index')
        else:
            return render(request, 'login.html')    
    else:
        if request.user.is_authenticated:
            return redirect('boards:index')
        else:
            return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    return redirect('boards:index')

jango/Day18/chatproject/accounts/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
<link rel="stylesheet" href="https://getbootstrap.com/docs/4.4/examples/sign-in/signin.css" >   


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body class="text-center">
    <form class="form-signin" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input  name="username" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <a href="{% url 'accounts:signup' %}" class="btn btn-lg btn-info btn-block" type="submit">Sign up</a>

  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</body>
</html>

jango/Day18/chatproject/accounts/templates/signup.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
<link rel="stylesheet" href="https://getbootstrap.com/docs/4.4/examples/sign-in/signin.css" >   


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body class="text-center">
    <form class="form-signin" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken"  value="{{csrf_token}}">
  <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input name="username" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input name="password1" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
  <input name="password2" type="password" id="inputPassword" class="form-control" placeholder="Password check" required>

  <div class="checkbox mb-3">
   
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</body>
</html>

jango/Day18/chatproject/boards/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://js.pusher.com/5.0/pusher.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Navbar</a>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:logout' %}">{{user.username}}</a>
            {% else %}
            <a class="nav-link" href="{% url 'accounts:login' %}">Sign in</a>
            {% endif %}
          </form>
        </div>
      </nav>







 {% block content %}
 {% endblock %}
 <script
 src="https://code.jquery.com/jquery-3.4.1.min.js"
 integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
 crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% block script %}
{% endblock %}
</body>
</html>

jango/Day18/chatproject/boards/templates/index.html
{% extends 'base.html' %}
{% block content %}


<div class="container mt-5">
    <h1>CHAT CHAT CHAT 서버버버버</h1>
</div>

<div class="container">
    <div class="row">
        <table class="table table-hover table-dark text-center">
            <thead>
                <tr>
                    <th scope="col" width="5%">#</th>
                    <th scope="col" width="50%">채팅방</th>
                    <th scope="col" width="25%">방장</th>
                    <th scope="col" width="20%">참여인원</th>
                </tr>
            </thead>
            <tbody class="room-list">
                {% for room in rooms%}
                <tr onclick="location.href='/boards/{{room.id}}';">
                    <th scope="row">{{room.id}}</th>
                    <td>{{room.title}}</td>
                    <td>{{room.master}}</td>
                    <td><span id="room-{{room.id}}-count">{{room.users.all.count}}</span>/{{room.max_connection}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    {%if user.is_authenticated %}
    <div class="row">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            새 채팅방 만들기
        </button>
    </div>
    {% endif %}
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">채팅방 만들기</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="create-room-form">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon3">채팅방 제목</span>
                        </div>
                        <input name="room-title" type="text" class="form-control" id="basic-url"
                            aria-describedby="basic-addon3">
                    </div>
                    <div class="input-group">
                        <input name="room-max-count" type="number" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    <button id="create-room" type="button" class="btn btn-primary" data-dismiss="modal">채팅방 생성</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<!-- 자바스크립트 -->
{% block script %}
<script>
    $(function () {
        // Enable pusher logging - don't include this in production
        Pusher.logToConsole = false;

        var pusher = new Pusher('96c64311e075281861fb', {
            cluster: 'ap3',
            forceTLS: true
        });

        var channel = pusher.subscribe('main');
        channel.bind('create-room', function (data) {
            console.log(JSON.stringify(data));
            var room = `<tr onclick="location.href='/boards/${data.id}'">
                    <tr>
                    <th scope="row">${data.id}</th>
                    <td>${data.title}</td>
                    <td>{${data.master}</td>
                    <td><span id="room-${data.id}-count">${data.current_connection}</span>${data.current_connection}/${data.max_connection}</td>
                    
                </tr>`
            $('.room-list').append(room);

        channel.bind('update-room',function(data){
            $(`#room-${data.room_id}-count`).text(data.current_connection);
        })
        });

















        $('#create-room').on('click', function () {
            console.log("채팅방 생성")
            // room에 대한 정보를 변수에 저장해서
            var room_data = $('#create-room-form').serialize();
            // 서버로 room 생성을 요청함
            console.log(room_data);
            $.ajax({
                url: '{% url "boards:index" %}',
                method: 'POST',
                data: room_data,
                success: function (data) {
                    console.log("생성")
                },
                error: function (data) {
                    console.log(data);
                }
            })
            // 정상 응답인지만 체크

        })
    })
</script>
{% endblock %}

jango/Day18/chatproject/boards/templates/show.html
{% extends 'base.html' %}

{%block content%}
<div class="container mt-5">
        <div class="row">
            <h1>{{room.title}}</h1>
            <div class="col-12 chat-messages" style="overflow:auto; width: 100%; height: 250px;">
                {% for message in messages %}
                <p>{{message.user.username}}님의 메세지:{{message.contents}} </p>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <form id="chat-form">
                <div class="row">
                <div class="col-10">
                    <input type="text" class="form-control">
                </div>
                <div class="col-2 text-center">
                    <button type="submit" class="btn btn-success">확인</button>
                </div>
                <div>
            </form>
        </div>
        <div class="row">
        <a href="{% url 'boards:exit' room.id %}" class="btn btn-warning">나가기</a>
        </div>>
    </div>
{%endblock%}

{% block script %}
<script>


$(function(){

    Pusher.logToConsole = false;
$('.chat-messages').scrollTop($('.chat-messages')[0].scrollHeight);
var pusher = new Pusher('96c64311e075281861fb', {
    cluster: 'ap3',
    forceTLS: true
});

var channel = pusher.subscribe('{{room.code}}');
channel.bind('chat',function(data){
    console.log(data);
    $('.chat-messages').append(`<p>${data.user}님의 메세지:${data.contents}</p>`)
    $('.chat-messages').scrollTop($('.chat-messages')[0].scrollHeight);
    // 메세지가 새로 써도 맨 아래에 포인트를 줘서 아래에 포인트를 줍니다.   
})



    $('#chat-form').on('submit',function(e){
        e.preventDefault();
        var room_id = '{{room.id}}'
        var text=$(this).find('input').val();
        $(this).find('input').val('');

        $.ajax({
            url:'{% url "boards:chat" room.id %}',
            method:'POST',
            data:{
                contents:text,
                csrfmiddlewaretoken: '{{csrf_token}}'
            },
            success: function(data){
                console.log("성공");
            },
            error:function(data){
                console.log("실패")
            }
        })
    })
})

</script>

{% endblock %}